version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: yarn test
